grave:
  block-beneath:
    type: MINECRAFT_PODZOL
    breakable: false
  armor-stand:
    headpos:
      x: 90.0
      y: 0.0
      z: 0.0
    relative-location:
      x: 0.0
      y: -1.25
      z: 0.0
    invisible: true
    gravity: false
  time: 21600 # 6 Hours in seconds
db: eternalfortune.sqlite